cc_library(
    name = "value_or_error",
    srcs = ["value_or_error.cc"],
    hdrs = ["value_or_error.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/language:ghost_type",
        "//src/language:ghost_type_class",
        "//src/language:overload",
        "//src/language:safe_types",
        "//src/language:wstring",
        "//src/language/lazy_string",
        "//src/language/lazy_string:append",
        "//src/language/lazy_string:char_buffer",
        "//src/tests",
    ],
)

cc_library(
    name = "view",
    hdrs = ["view.h"],
    visibility = ["//visibility:public"],
)
