cc_library(
    name = "value_or_error",
    srcs = ["value_or_error.cc"],
    hdrs = ["value_or_error.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/language:ghost_type",
        "//src/language:overload",
        "//src/language:safe_types",
        "//src/language:wstring",
        "//src/tests",
    ],
)
