cc_library(
    name = "decaying_counter",
    srcs = ["decaying_counter.cc"],
    hdrs = ["decaying_counter.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/infrastructure:time",
    ],
)
