#define COMMA                            1
#define EQ                               2
#define OR                               3
#define AND                              4
#define EQUALS                           5
#define NOT_EQUALS                       6
#define LESS_THAN                        7
#define GREATER_THAN                     8
#define PLUS                             9
#define MINUS                           10
#define DIVIDE                          11
#define TIMES                           12
#define NOT                             13
#define LPAREN                          14
#define RPAREN                          15
#define DOT                             16
#define ELSE                            17
#define SEMICOLON                       18
#define RETURN                          19
#define LBRACKET                        20
#define RBRACKET                        21
#define SYMBOL                          22
#define WHILE                           23
#define IF                              24
#define BOOL                            25
#define INTEGER                         26
#define STRING                          27
